### ISSUE TITLE
在页面中把q-tabbar作为根节点会导致onShow和onHide这两个页面的生命周期函数无法触发

### ISSUE THREAD

**Issue by Ping-Gao** [quickappcn/qaui#3]

**Comment by stevendong** [comment]
实测，没有出现这个BUG，需要提供下复现demo

**Comment by Ping-GAO** [comment]
在我本地环境，这个例子用华为快应用IDE编译会出现这个问题。
[复现repo](http://gitlab.ziquntech.com:20080/gaoping/test-demo-quickapp)

**Comment by Ping-GAO** [comment]
> 实测，没有出现这个BUG，需要提供下复现demo

**Comment by Ping-GAO** [comment]
> 实测，没有出现这个BUG，需要提供下复现demo

在我本地环境，这个例子用华为快应用IDE编译会出现这个问题。
[复现repo](http://gitlab.ziquntech.com:20080/gaoping/test-demo-quickapp)
