### ISSUE TITLE
用华为快应用ide在页面中把q-tabbar作为页面根节点会导致onShow和onHide这两个页面的生命周期函数无法触发

### ISSUE THREAD

**Issue by Ping-Gao** [quickappcn/qaui#4]
之前issues不小心误点了close，在我本地环境，这个例子用华为快应用IDE编译会出现这个问题。
[复现repo](http://gitlab.ziquntech.com:20080/gaoping/test-demo-quickapp)

**Comment by stevendong** [comment]
😢 老哥，华为打包和联盟用的不是一套，很容易出和联盟各种表现不一致的问题，建议还是用联盟IDE打包吧

**Comment by Ping-Gao** [comment]
> 😢 老哥，华为打包和联盟用的不是一套，很容易出和联盟各种表现不一致的问题，建议还是用联盟IDE打包吧

👌

**Comment by Ping-Gao** [comment]
> 😢 老哥，华为打包和联盟用的不是一套，很容易出和联盟各种表现不一致的问题，建议还是用联盟IDE打包吧

是用的联盟ide打包发布的，上线以后发现在华为上有这个问题。然后用华为的ide复现出这个问题。

**Comment by stevendong** [comment]
😿 建议单独兼容华为的机器，华为目前引擎版本1070+，联盟已经1090+了
